You could use this notebook on [Google Colab](https://colab.research.google.com/) with a GPU Hardware Accelerator runtype.

# Setup

In [1]:
#For some reason pip3 install -r requirements.txt doesn't work on Colab
! pip3 install -r requirements.txt

Requirement already satisfied: colorama==0.4.6 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from -r requirements.txt (line 1)) (0.4.6)
Requirement already satisfied: pandas==2.1.1 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from -r requirements.txt (line 2)) (2.1.1)
Requirement already satisfied: sbrscrape==0.0.10 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from -r requirements.txt (line 3)) (0.0.10)
Requirement already satisfied: tensorflow==2.14.0 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from -r requirements.txt (line 4)) (2.14.0)
Requirement already satisfied: xgboost==2.0.0 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from -r requirements.txt (line 6)) (2.0.0)
Requirement already satisfied: tqdm==4.66.1 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from -r requirements.txt (line 7)) (4.66.1)
Requirement already satisfied: flask==3.0.0 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from -r requirements.txt (line 8)) (3.0.0)
Requirement already satisfied: scikit-learn==1.3.1 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from -r requirements.txt (line 9)) (1.3.1)
Requirement already satisfied: toml==0.10.2 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from -r requirements.txt (line 10)) (0.10.2)
Requirement already satisfied: matplotlib in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from -r requirements.txt (line 11)) (3.10.1)
Requirement already satisfied: seaborn in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from -r requirements.txt (line 12)) (0.13.2)
Requirement already satisfied: nba_api in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from -r requirements.txt (line 13)) (1.8.0)
Requirement already satisfied: tzdata>=2022.1 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from pandas==2.1.1->-r requirements.txt (line 2)) (2025.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from pandas==2.1.1->-r requirements.txt (line 2)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from pandas==2.1.1->-r requirements.txt (line 2)) (2025.1)
Requirement already satisfied: numpy>=1.22.4 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from pandas==2.1.1->-r requirements.txt (line 2)) (1.26.4)
Requirement already satisfied: tensorflow-intel==2.14.0 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from tensorflow==2.14.0->-r requirements.txt (line 4)) (2.14.0)
Requirement already satisfied: scipy in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from xgboost==2.0.0->-r requirements.txt (line 6)) (1.15.2)
Requirement already satisfied: blinker>=1.6.2 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from flask==3.0.0->-r requirements.txt (line 8)) (1.9.0)
Requirement already satisfied: Jinja2>=3.1.2 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from flask==3.0.0->-r requirements.txt (line 8)) (3.1.6)
Requirement already satisfied: Werkzeug>=3.0.0 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from flask==3.0.0->-r requirements.txt (line 8)) (3.1.3)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from flask==3.0.0->-r requirements.txt (line 8)) (2.2.0)
Requirement already satisfied: click>=8.1.3 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from flask==3.0.0->-r requirements.txt (line 8)) (8.1.8)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from scikit-learn==1.3.1->-r requirements.txt (line 9)) (3.5.0)
Requirement already satisfied: joblib>=1.1.1 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from scikit-learn==1.3.1->-r requirements.txt (line 9)) (1.4.2)
Requirement already satisfied: tensorboard<2.15,>=2.14 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (2.14.1)
Requirement already satisfied: ml-dtypes==0.2.0 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (0.2.0)
Requirement already satisfied: google-pasta>=0.1.1 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (0.2.0)
Requirement already satisfied: packaging in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (24.2)
Requirement already satisfied: h5py>=2.9.0 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (3.13.0)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (3.4.0)
Requirement already satisfied: setuptools in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (63.2.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (1.6.3)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (4.12.2)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (0.6.0)
Requirement already satisfied: flatbuffers>=23.5.26 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (25.2.10)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (1.70.0)
Requirement already satisfied: six>=1.12.0 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (1.17.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (2.1.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (18.1.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (4.25.6)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (2.5.0)
Requirement already satisfied: tensorflow-estimator<2.15,>=2.14.0 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (2.14.0)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (1.14.1)
Requirement already satisfied: keras<2.15,>=2.14.0 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (2.14.0)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (0.31.0)
Requirement already satisfied: pillow>=8 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from matplotlib->-r requirements.txt (line 11)) (11.1.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from matplotlib->-r requirements.txt (line 11)) (1.4.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from matplotlib->-r requirements.txt (line 11)) (1.3.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from matplotlib->-r requirements.txt (line 11)) (4.56.0)
Requirement already satisfied: cycler>=0.10 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from matplotlib->-r requirements.txt (line 11)) (0.12.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from matplotlib->-r requirements.txt (line 11)) (3.2.3)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from nba_api->-r requirements.txt (line 13)) (2.32.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from Jinja2>=3.1.2->flask==3.0.0->-r requirements.txt (line 8)) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from requests<3.0.0,>=2.32.3->nba_api->-r requirements.txt (line 13)) (3.4.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from requests<3.0.0,>=2.32.3->nba_api->-r requirements.txt (line 13)) (2025.1.31)
Requirement already satisfied: idna<4,>=2.5 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from requests<3.0.0,>=2.32.3->nba_api->-r requirements.txt (line 13)) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from requests<3.0.0,>=2.32.3->nba_api->-r requirements.txt (line 13)) (2.3.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (0.45.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (2.38.0)
Requirement already satisfied: markdown>=2.6.8 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (3.7)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (0.7.2)
Requirement already satisfied: google-auth-oauthlib<1.1,>=0.5 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (1.0.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (0.4.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (5.5.2)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (2.0.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (0.6.1)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\order\repos\nba-machine-learning-sports-betting\myvenv\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow==2.14.0->-r requirements.txt (line 4)) (3.2.2)

[notice] A new release of pip available: 22.2.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

# Exploratory Data Analysis
A key to the usefulness of this program is understanding the dataset. Knowing the limitations of the current data adds context to the predictions made by the program.

In [20]:
# Import necessary libraries
import pandas as pd
import numpy as np
from nba_api.stats.endpoints import teamgamelog, cumestatsteamgames, cumestatsteam, gamerotation, boxscoreadvancedv3, leaguegamefinder
from nba_api.stats.static import teams, players
import matplotlib.pyplot as plt
import seaborn as sns
import json

pd.option_context('mode.chained_assignment', None)
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [3]:
nba_teams = teams.get_teams()
print(f"Number of teams fetched: {len(nba_teams)}")
celtics = [team for team in nba_teams if team['abbreviation'] == 'BOS'][0]
celtics_id = celtics['id']

# query for games where the celtics were playing
gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable=celtics_id)
games = gamefinder.get_data_frames()[0]
# Will only give stats for the Celtics, not the opponent
games.columns

Number of teams fetched: 30

Index(['SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID',
       'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'PTS', 'FGM', 'FGA', 'FG_PCT',
       'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB',
       'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PLUS_MINUS'],
      dtype='object')

In [4]:
games.groupby(games.SEASON_ID.str[-4:])[['GAME_ID']].count()

           GAME_ID
SEASON_ID
1983           105
1984           103
1985           100
1986           105
1987            99
1988            85
1989            87
1990            93
1991            92
1992            86
1993            82
1994            86
1995            82
1996            82
1997            82
1998            50
1999            82
2000            82
2001            98
2002            92
2003            87
2004            92
2005            90
2006            90
2007           120
2008           104
2009           114
2010           104
2011            88
2012           105
2013            95
2014            99
2015           103
2016           115
2017           113
2018           101
2019           102
2020            80
2021           115
2022           111
2023           111
2024            83

In [8]:
# get all the games
result = leaguegamefinder.LeagueGameFinder(league_id_nullable='00', season_type_nullable='Regular Season')
all_games = result.get_data_frames()[0]
# Example game
full_game = all_games[all_games.GAME_ID == '0022401058']
full_game

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
31,22024,1610612756,PHX,Phoenix Suns,0022401058,2025-03-26,PHX vs. BOS,L,239,102,36,87,0.414,13,41,0.317,17,21,0.810,11,27,38,22,7,3,13,18,-30.0
39,22024,1610612738,BOS,Boston Celtics,0022401058,2025-03-26,BOS @ PHX,W,239,132,45,89,0.506,22,52,0.423,20,22,0.909,11,37,48,33,8,7,10,18,30.0

In [13]:
# sort games by date
all_games['GAME_DATE'] = pd.to_datetime(all_games['GAME_DATE'], format='%Y-%m-%d')
sorted_games = all_games.sort_values(['TEAM_ID', 'GAME_DATE'], ascending=True)
print(sorted_games.tail(5))

    SEASON_ID     TEAM_ID TEAM_ABBREVIATION          TEAM_NAME     GAME_ID  \
126     22024  1610612766               CHA  Charlotte Hornets  0022401010
113     22024  1610612766               CHA  Charlotte Hornets  0022401017
85      22024  1610612766               CHA  Charlotte Hornets  0022401032
50      22024  1610612766               CHA  Charlotte Hornets  0022401045
0       22024  1610612766               CHA  Charlotte Hornets  0022401069

     GAME_DATE      MATCHUP WL  MIN  PTS  FGM  FGA  FG_PCT  FG3M  FG3A  \
126 2025-03-20  CHA vs. NYK  W  239  115   43   88   0.489    15    32
113 2025-03-21    CHA @ OKC  L  241  106   37   80   0.463    19    41
85  2025-03-23    CHA @ MIA  L  239  105   41   87   0.471    11    33
50  2025-03-25  CHA vs. ORL  L  241  104   37   88   0.420    14    34
0   2025-03-28    CHA @ TOR  L  239   97   39   96   0.406     9    31

     FG3_PCT  FTM  FTA  FT_PCT  OREB  DREB  REB  AST  STL  BLK  TOV  PF  \
126    0.469   14   17   0.824    11    41   52   25    1    3   11  20
113    0.463   13   13   1.000     6    23   29   29    6    4   16  13
85     0.333   12   13   0.923    12    28   40   24    5    4   19  15
50     0.412   16   21   0.762     8    30   38   26    4    3   11  22
0      0.290   10   15   0.667    13    43   56   29    5    5   17  12

     PLUS_MINUS
126        17.0
113       -35.0
85        -17.0
50         -7.0
0         -11.0

In [29]:
season_2024 = sorted_games[sorted_games['SEASON_ID']=='22024']

# Create columns representing the rolling average of the previous 5 games
features = ['PTS', 'FGM', 'FG_PCT', 'FG3M', 'FG3_PCT', 'FTM', 'FT_PCT', 'OREB', 'DREB', 'AST', 'STL', 'BLK', 'TOV', 'PF']

teams = season_2024['TEAM_ABBREVIATION'].unique()
for team in teams:
    for feature in features:
        season_2024.loc[season_2024['TEAM_ABBREVIATION']==team, [f'rolling_{feature}']] = season_2024[season_2024['TEAM_ABBREVIATION']==team].shift(1).rolling(window=5, min_periods=0)[feature].mean()
season_2024.head(5)

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS,rolling_PTS,rolling_FGM,rolling_FG_PCT,rolling_FG3M,rolling_FG3_PCT,rolling_FTM,rolling_FT_PCT,rolling_OREB,rolling_DREB,rolling_AST,rolling_STL,rolling_BLK,rolling_TOV,rolling_PF
2180,22024,1610612737,ATL,Atlanta Hawks,0022400064,2024-10-23,ATL vs. BKN,W,241,120,39,80,0.488,9,28,0.321,33,46,0.717,12,33,45,25,12,9,16,20,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2152,22024,1610612737,ATL,Atlanta Hawks,0022400079,2024-10-25,ATL vs. CHA,W,240,125,39,81,0.481,14,38,0.368,33,38,0.868,7,32,39,25,11,9,13,28,5.0,120.000000,39.00,0.4880,9.0,0.321000,33.000000,0.717000,12.0,33.000000,25.000000,12.0,9.000000,16.0,20.000000
2130,22024,1610612737,ATL,Atlanta Hawks,0022400100,2024-10-27,ATL @ OKC,L,240,104,36,91,0.396,10,31,0.323,22,29,0.759,17,32,49,24,7,4,19,23,-24.0,122.500000,39.00,0.4845,11.5,0.344500,33.000000,0.792500,9.5,32.500000,25.000000,11.5,9.000000,14.5,24.000000
2114,22024,1610612737,ATL,Atlanta Hawks,0022400103,2024-10-28,ATL vs. WAS,L,240,119,39,81,0.481,15,40,0.375,26,36,0.722,6,33,39,32,12,7,16,22,-2.0,116.333333,38.00,0.4550,11.0,0.337333,29.333333,0.781333,12.0,32.333333,24.666667,10.0,7.333333,16.0,23.666667
2083,22024,1610612737,ATL,Atlanta Hawks,0022400121,2024-10-30,ATL @ WAS,L,240,120,45,95,0.474,12,39,0.308,18,21,0.857,12,29,41,28,10,3,15,19,-13.0,117.000000,38.25,0.4615,12.0,0.346750,28.500000,0.766500,10.5,32.500000,26.500000,10.5,7.250000,16.0,23.250000

In [30]:
season_2024[season_2024['TEAM_ABBREVIATION']=='BOS']

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS,rolling_PTS,rolling_FGM,rolling_FG_PCT,rolling_FG3M,rolling_FG3_PCT,rolling_FTM,rolling_FT_PCT,rolling_OREB,rolling_DREB,rolling_AST,rolling_STL,rolling_BLK,rolling_TOV,rolling_PF
2201,22024,1610612738,BOS,Boston Celtics,0022400061,2024-10-22,BOS vs. NYK,W,240,132,48,95,0.505,29,61,0.475,7,8,0.875,11,29,40,33,6,3,3,15,23.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2179,22024,1610612738,BOS,Boston Celtics,0022400073,2024-10-24,BOS @ WAS,W,240,122,42,90,0.467,17,45,0.378,21,27,0.778,12,37,49,21,7,3,14,19,20.0,132.00,48.000000,0.505000,29.000000,0.4750,7.00,0.87500,11.0,29.0,33.000000,6.000000,3.00,3.00,15.000000
2151,22024,1610612738,BOS,Boston Celtics,0022400089,2024-10-26,BOS @ DET,W,239,124,38,90,0.422,22,48,0.458,26,30,0.867,13,24,37,19,10,6,10,16,6.0,127.00,45.000000,0.486000,23.000000,0.4265,14.00,0.82650,11.5,33.0,27.000000,6.500000,3.00,8.50,17.000000
2106,22024,1610612738,BOS,Boston Celtics,0022400104,2024-10-28,BOS vs. MIL,W,242,119,43,87,0.494,18,47,0.383,15,19,0.789,4,34,38,24,5,5,12,18,11.0,126.00,42.666667,0.464667,22.666667,0.4370,18.00,0.84000,12.0,30.0,24.333333,7.666667,4.00,9.00,16.666667
2086,22024,1610612738,BOS,Boston Celtics,0022400119,2024-10-30,BOS @ IND,L,266,132,44,109,0.404,19,57,0.333,25,31,0.806,18,33,51,23,11,5,14,19,-3.0,124.25,42.750000,0.472000,21.500000,0.4235,17.25,0.82725,10.0,31.0,24.250000,7.000000,4.25,9.75,17.000000
2061,22024,1610612738,BOS,Boston Celtics,0022400132,2024-11-01,BOS @ CHA,W,242,124,41,86,0.477,13,42,0.310,29,35,0.829,11,30,41,21,12,5,10,13,15.0,125.80,43.000000,0.458400,21.000000,0.4054,18.80,0.82300,11.6,31.4,24.000000,7.800000,4.40,10.60,17.400000
2025,22024,1610612738,BOS,Boston Celtics,0022400141,2024-11-02,BOS @ CHA,W,240,113,36,82,0.439,16,52,0.308,25,28,0.893,8,36,44,23,4,4,15,17,10.0,124.20,41.600000,0.452800,17.800000,0.3724,23.20,0.81380,11.6,31.6,21.600000,9.000000,4.80,12.00,17.000000
1995,22024,1610612738,BOS,Boston Celtics,0022400157,2024-11-04,BOS @ ATL,W,239,123,48,99,0.485,18,55,0.327,9,13,0.692,11,39,50,27,15,7,12,14,30.0,122.40,40.400000,0.447200,17.600000,0.3584,24.00,0.83680,10.8,31.4,22.000000,8.400000,5.00,12.20,16.600000
1969,22024,1610612738,BOS,Boston Celtics,0022400172,2024-11-06,BOS vs. GSW,L,240,112,38,90,0.422,19,54,0.352,17,21,0.810,13,34,47,22,5,3,12,18,-6.0,122.20,42.400000,0.459800,16.800000,0.3322,20.60,0.80180,10.4,34.4,23.600000,9.400000,5.20,12.60,16.200000
1950,22024,1610612738,BOS,Boston Celtics,0022400187,2024-11-08,BOS vs. BKN,W,266,108,39,90,0.433,14,53,0.264,16,19,0.842,4,35,39,23,7,9,13,15,4.0,120.80,41.400000,0.445400,17.000000,0.3260,21.00,0.80600,12.2,34.4,23.200000,9.400000,4.80,12.60,16.200000
1922,22024,1610612738,BOS,Boston Celtics,0022400202,2024-11-10,BOS @ MIL,W,240,113,35,86,0.407,19,50,0.380,24,27,0.889,8,34,42,27,5,2,12,16,6.0,116.00,40.400000,0.451200,16.000000,0.3122,19.20,0.81320,9.4,34.8,23.200000,8.600000,5.60,12.40,15.400000
1882,22024,1610612738,BOS,Boston Celtics,0022400001,2024-11-12,BOS vs. ATL,L,239,116,38,75,0.507,18,45,0.400,22,27,0.815,6,28,34,28,7,5,20,12,-1.0,113.80,39.200000,0.437200,17.200000,0.3262,18.20,0.82520,8.8,35.6,24.400000,7.200000,5.00,12.80,16.000000
1861,22024,1610612738,BOS,Boston Celtics,0022400218,2024-11-13,BOS @ BKN,W,241,139,50,93,0.538,22,46,0.478,17,24,0.708,12,33,45,35,7,6,7,17,25.0,114.40,39.600000,0.450800,17.600000,0.3446,17.60,0.80960,8.4,34.0,25.400000,7.800000,5.20,13.80,15.000000
1827,22024,1610612738,BOS,Boston Celtics,0022400230,2024-11-16,BOS vs. TOR,W,265,126,44,99,0.444,21,61,0.344,17,19,0.895,14,28,42,30,2,6,9,20,3.0,117.60,40.000000,0.461400,18.400000,0.3748,19.20,0.81280,8.6,32.8,27.000000,6.200000,5.00,12.80,15.600000
1773,22024,1610612738,BOS,Boston Celtics,0022400021,2024-11-19,BOS vs. CLE,W,240,120,44,86,0.512,22,41,0.537,10,14,0.714,9,33,42,32,4,4,13,19,3.0,120.40,41.200000,0.465800,18.800000,0.3732,19.20,0.82980,8.8,31.6,28.600000,5.600000,5.60,12.20,16.000000
1741,22024,1610612738,BOS,Boston Celtics,0022400028,2024-11-22,BOS @ WAS,W,240,108,36,85,0.424,11,46,0.239,25,32,0.781,10,33,43,22,11,7,12,19,12.0,122.80,42.200000,0.481600,20.400000,0.4278,18.00,0.80420,9.8,31.2,30.400000,5.000000,4.60,12.20,16.800000
1711,22024,1610612738,BOS,Boston Celtics,0022400271,2024-11-24,BOS vs. MIN,W,239,107,37,87,0.425,21,56,0.375,12,15,0.800,8,32,40,25,5,7,6,23,2.0,121.80,42.400000,0.485000,18.800000,0.3996,18.20,0.78260,10.2,31.0,29.400000,6.200000,5.60,12.20,17.400000
1689,22024,1610612738,BOS,Boston Celtics,0022400281,2024-11-25,BOS vs. LAC,W,240,126,45,88,0.511,22,51,0.431,14,20,0.700,8,39,47,33,10,11,11,12,32.0,120.00,42.200000,0.468600,19.400000,0.3946,16.20,0.77960,10.6,31.8,28.800000,5.800000,6.00,9.40,19.600000
1636,22024,1610612738,BOS,Boston Celtics,0022400047,2024-11-29,BOS @ CHI,W,241,138,49,98,0.500,23,54,0.426,17,23,0.739,11,40,51,24,6,2,9,13,9.0,117.40,41.200000,0.463200,19.400000,0.3852,15.60,0.77800,9.8,33.0,28.400000,6.400000,7.00,10.20,18.600000
1609,22024,1610612738,BOS,Boston Celtics,0022400307,2024-12-01,BOS @ CLE,L,240,111,38,95,0.400,17,49,0.347,18,19,0.947,10,36,46,17,11,6,8,19,-4.0,119.80,42.200000,0.474400,19.800000,0.4016,15.60,0.74680,9.2,35.4,27.200000,7.200000,6.20,10.20,17.200000
1591,22024,1610612738,BOS,Boston Celtics,0022400316,2024-12-02,BOS vs. MIA,W,240,108,39,89,0.438,19,55,0.345,11,13,0.846,14,40,54,25,5,9,14,20,19.0,118.00,41.000000,0.452000,18.800000,0.3636,17.20,0.79340,9.4,36.0,24.200000,8.600000,6.60,9.20,17.200000
1564,22024,1610612738,BOS,Boston Celtics,0022400319,2024-12-04,BOS vs. DET,W,240,130,45,94,0.479,21,53,0.396,19,25,0.760,14,29,43,30,11,7,16,14,10.0,118.00,41.600000,0.454800,20.400000,0.3848,14.40,0.80640,10.2,37.4,24.800000,7.400000,7.00,9.60,17.400000
1526,22024,1610612738,BOS,Boston Celtics,0022400335,2024-12-06,BOS vs. MIL,W,238,111,40,87,0.460,17,53,0.321,14,16,0.875,7,34,41,27,5,6,6,18,6.0,122.60,43.200000,0.465600,20.400000,0.3890,15.80,0.79840,11.4,36.8,25.800000,8.600000,7.00,11.60,15.600000
1516,22024,1610612738,BOS,Boston Celtics,0022400345,2024-12-07,BOS vs. MEM,L,239,121,42,105,0.400,18,60,0.300,19,28,0.679,15,36,51,26,6,7,13,16,-6.0,119.60,42.200000,0.455400,19.400000,0.3670,15.80,0.83340,11.2,35.8,24.600000,7.600000,6.00,10.60,16.800000
1476,22024,1610612738,BOS,Boston Celtics,0022401205,2024-12-12,BOS vs. DET,W,241,123,46,90,0.511,20,48,0.417,11,13,0.846,8,43,51,34,6,4,14,9,24.0,116.20,40.800000,0.435400,18.400000,0.3418,16.20,0.82140,12.0,35.0,25.000000,7.600000,7.00,11.40,17.400000
1445,22024,1610612738,BOS,Boston Celtics,0022401217,2024-12-15,BOS @ WAS,W,239,112,40,93,0.430,18,46,0.391,14,24,0.583,16,40,56,26,11,5,18,15,14.0,118.60,42.400000,0.457600,19.000000,0.3558,14.80,0.80120,11.6,36.4,28.400000,6.600000,6.60,12.60,15.400000
1407,22024,1610612738,BOS,Boston Celtics,0022400363,2024-12-19,BOS vs. CHI,L,239,108,38,97,0.392,14,56,0.250,18,21,0.857,11,34,45,21,6,8,4,13,-9.0,119.40,42.600000,0.456000,18.800000,0.3650,15.40,0.74860,12.0,36.4,28.600000,7.800000,5.80,13.40,14.400000
1372,22024,1610612738,BOS,Boston Celtics,0022400381,2024-12-21,BOS @ CHI,W,240,123,48,100,0.480,15,45,0.333,12,14,0.857,17,42,59,27,8,4,12,12,25.0,115.00,41.200000,0.438600,17.400000,0.3358,15.20,0.76800,11.4,37.4,26.800000,6.800000,6.00,11.00,14.200000
1350,22024,1610612738,BOS,Boston Celtics,0022400393,2024-12-23,BOS @ ORL,L,239,104,37,84,0.440,8,33,0.242,22,27,0.815,8,33,41,13,13,5,18,16,-4.0,117.40,42.800000,0.442600,17.000000,0.3382,14.80,0.76440,13.4,39.0,26.800000,7.400000,5.60,12.20,13.000000
1327,22024,1610612738,BOS,Boston Celtics,0022400407,2024-12-25,BOS vs. PHI,L,239,114,43,95,0.453,20,49,0.408,8,13,0.615,13,38,51,24,3,4,13,18,-4.0,114.00,41.800000,0.450600,15.000000,0.3266,15.40,0.79160,12.0,38.4,24.200000,8.800000,5.20,13.20,13.000000
1299,22024,1610612738,BOS,Boston Celtics,0022400420,2024-12-27,BOS vs. IND,W,241,142,47,92,0.511,23,56,0.411,25,29,0.862,18,34,52,31,9,6,10,19,37.0,112.20,41.200000,0.439000,15.000000,0.3248,14.80,0.74540,13.0,37.4,22.200000,8.200000,5.20,13.00,14.800000
1263,22024,1610612738,BOS,Boston Celtics,0022400437,2024-12-29,BOS vs. IND,L,239,114,43,93,0.462,16,54,0.296,12,19,0.632,8,33,41,26,6,6,8,22,-9.0,118.20,42.600000,0.455200,16.000000,0.3288,17.00,0.80120,13.4,36.2,23.200000,7.800000,5.40,11.40,15.600000
1241,22024,1610612738,BOS,Boston Celtics,0022400449,2024-12-31,BOS vs. TOR,W,239,125,47,87,0.540,22,43,0.512,9,15,0.600,11,38,49,29,14,7,13,10,54.0,119.40,43.600000,0.469200,16.400000,0.3380,15.80,0.75620,12.8,36.0,24.200000,7.800000,5.00,12.20,17.400000
1215,22024,1610612738,BOS,Boston Celtics,0022400464,2025-01-02,BOS @ MIN,W,241,118,46,92,0.500,22,57,0.386,4,6,0.667,10,21,31,30,9,4,3,16,3.0,119.80,43.400000,0.481200,17.800000,0.3738,15.20,0.70480,11.6,35.2,24.600000,9.000000,5.60,12.40,17.000000
1191,22024,1610612738,BOS,Boston Celtics,0022400471,2025-01-03,BOS @ HOU,W,242,109,39,77,0.506,19,39,0.487,12,18,0.667,12,29,41,20,6,8,14,13,23.0,122.60,45.200000,0.493200,20.600000,0.4026,11.60,0.67520,12.0,32.8,28.000000,8.200000,5.40,9.40,17.000000
1167,22024,1610612738,BOS,Boston Celtics,0022400487,2025-01-05,BOS @ OKC,L,241,92,31,85,0.365,9,46,0.196,21,24,0.875,12,36,48,17,6,5,16,18,-13.0,121.60,44.400000,0.503800,20.400000,0.4184,12.40,0.68560,11.8,31.0,27.200000,8.800000,6.20,9.60,16.000000
1140,22024,1610612738,BOS,Boston Celtics,0022400507,2025-01-07,BOS @ DEN,W,241,118,44,88,0.500,12,35,0.343,18,20,0.900,11,30,41,30,11,7,11,13,12.0,111.60,41.200000,0.474600,17.600000,0.3754,11.60,0.68820,10.6,31.4,24.400000,8.200000,6.00,10.80,15.800000
1088,22024,1610612738,BOS,Boston Celtics,0022400528,2025-01-10,BOS vs. SAC,L,238,97,34,84,0.405,11,41,0.268,18,22,0.818,8,35,43,22,5,7,15,14,-17.0,112.40,41.400000,0.482200,16.800000,0.3848,12.80,0.74180,11.2,30.8,25.200000,9.200000,6.20,11.40,14.000000
1059,22024,1610612738,BOS,Boston Celtics,0022400542,2025-01-12,BOS vs. NOP,W,241,120,44,101,0.436,13,44,0.295,19,23,0.826,18,37,55,23,5,7,11,18,1.0,106.80,38.800000,0.455200,14.600000,0.3360,14.60,0.78540,10.6,30.2,23.800000,7.400000,6.20,11.80,14.800000
1021,22024,1610612738,BOS,Boston Celtics,0022400562,2025-01-15,BOS @ TOR,L,239,97,36,91,0.396,16,46,0.348,9,18,0.500,13,32,45,24,6,8,9,16,-13.0,107.20,38.400000,0.442400,12.800000,0.3178,17.60,0.81720,12.2,33.4,22.400000,6.600000,6.80,13.40,15.200000
998,22024,1610612738,BOS,Boston Celtics,0022400577,2025-01-17,BOS vs. ORL,W,240,121,42,80,0.525,17,37,0.459,20,22,0.909,11,30,41,25,6,3,10,23,27.0,104.80,37.800000,0.420400,12.200000,0.2900,17.00,0.78380,12.4,34.0,23.200000,6.600000,6.80,12.40,15.800000
971,22024,1610612738,BOS,Boston Celtics,0022400587,2025-01-18,BOS vs. ATL,L,265,115,40,104,0.385,15,52,0.288,20,23,0.870,17,36,53,23,13,6,14,18,-4.0,110.60,40.000000,0.452400,13.800000,0.3426,16.80,0.79060,12.2,32.8,24.800000,6.600000,6.40,11.20,16.800000
951,22024,1610612738,BOS,Boston Celtics,0022400604,2025-01-20,BOS @ GSW,W,239,125,49,92,0.533,20,48,0.417,7,8,0.875,8,42,50,33,8,9,9,8,40.0,110.00,39.200000,0.429400,14.400000,0.3316,17.20,0.78460,13.4,34.0,23.400000,7.000000,6.20,11.80,17.800000
923,22024,1610612738,BOS,Boston Celtics,0022400620,2025-01-22,BOS @ LAC,W,265,117,41,90,0.456,19,50,0.380,16,20,0.800,8,24,32,24,11,4,19,14,4.0,115.60,42.200000,0.455000,16.200000,0.3614,15.00,0.79600,13.4,35.4,25.600000,7.600000,6.60,10.60,16.600000
900,22024,1610612738,BOS,Boston Celtics,0022400629,2025-01-23,BOS @ LAL,L,239,96,35,91,0.385,14,41,0.341,12,18,0.667,11,31,42,23,5,6,7,17,-21.0,115.00,41.600000,0.459000,17.400000,0.3784,14.40,0.79080,11.4,32.8,25.800000,8.800000,6.00,12.20,15.800000
862,22024,1610612738,BOS,Boston Celtics,0022400635,2025-01-25,BOS @ DAL,W,241,122,44,103,0.427,20,52,0.385,14,19,0.737,17,34,51,33,4,5,5,24,15.0,114.80,41.400000,0.456800,17.000000,0.3770,15.00,0.82420,11.0,32.6,25.600000,8.600000,5.60,11.80,16.000000
847,22024,1610612738,BOS,Boston Celtics,0022400650,2025-01-27,BOS vs. HOU,L,239,112,39,80,0.488,15,39,0.385,19,20,0.950,7,34,41,21,4,4,14,20,-2.0,115.00,41.800000,0.437200,17.600000,0.3622,13.80,0.78980,12.2,33.4,27.200000,8.200000,6.00,10.80,16.200000
821,22024,1610612738,BOS,Boston Celtics,0022400666,2025-01-29,BOS vs. CHI,W,242,122,41,87,0.471,18,44,0.409,22,27,0.815,6,39,45,32,9,3,8,13,22.0,114.40,41.600000,0.457800,17.600000,0.3816,13.60,0.80580,10.2,33.0,26.800000,6.400000,5.60,10.80,16.600000
795,22024,1610612738,BOS,Boston Celtics,0022400683,2025-01-31,BOS @ NOP,W,240,118,42,84,0.500,16,41,0.390,18,26,0.692,5,30,35,32,12,7,13,16,2.0,113.80,40.000000,0.445400,17.200000,0.3800,16.60,0.79380,9.8,32.4,26.600000,6.600000,4.40,10.60,17.600000
757,22024,1610612738,BOS,Boston Celtics,0022400698,2025-02-02,BOS @ PHI,W,240,118,42,84,0.500,21,49,0.429,13,16,0.813,5,33,38,34,3,8,9,21,8.0,114.00,40.200000,0.454200,16.600000,0.3820,17.00,0.77220,9.2,33.6,28.200000,6.800000,5.00,9.40,18.000000
725,22024,1610612738,BOS,Boston Celtics,0022400710,2025-02-04,BOS @ CLE,W,240,112,40,98,0.408,17,48,0.354,15,18,0.833,15,38,53,26,10,6,12,21,7.0,118.40,41.600000,0.477200,18.000000,0.3996,17.20,0.80140,8.0,34.0,30.400000,6.400000,5.40,9.80,18.800000
691,22024,1610612738,BOS,Boston Celtics,0022400728,2025-02-06,BOS vs. DAL,L,243,120,46,89,0.517,16,37,0.432,12,15,0.800,11,29,40,30,2,6,14,17,-7.0,116.40,40.800000,0.473400,17.400000,0.3934,17.40,0.82060,7.6,34.8,29.000000,7.600000,5.60,11.20,18.200000
658,22024,1610612738,BOS,Boston Celtics,0022400748,2025-02-08,BOS @ NYK,W,241,131,46,85,0.541,19,39,0.487,20,24,0.833,11,37,48,21,6,7,10,21,27.0,118.00,42.200000,0.479200,17.600000,0.4028,16.00,0.79060,8.4,33.8,30.800000,7.200000,6.00,11.20,17.600000
638,22024,1610612738,BOS,Boston Celtics,0022400759,2025-02-10,BOS @ MIA,W,239,103,39,85,0.459,17,53,0.321,8,8,1.000,3,49,52,24,4,5,6,11,18.0,119.80,43.200000,0.493200,17.800000,0.4184,15.60,0.79420,9.4,33.4,28.600000,6.600000,6.80,11.60,19.200000
604,22024,1610612738,BOS,Boston Celtics,0022400769,2025-02-12,BOS vs. SAS,W,238,116,42,91,0.462,18,55,0.327,14,21,0.667,15,41,56,25,3,5,15,12,13.0,116.80,42.600000,0.485000,18.000000,0.4046,13.60,0.85580,9.0,37.2,27.000000,5.000000,6.40,10.20,18.200000
560,22024,1610612738,BOS,Boston Celtics,0022400789,2025-02-20,BOS @ PHI,W,240,124,43,89,0.483,24,54,0.444,14,15,0.933,11,38,49,33,3,6,10,16,20.0,116.40,42.600000,0.477400,17.400000,0.3842,13.80,0.82660,11.0,38.8,25.200000,5.000000,5.80,11.40,16.400000
522,22024,1610612738,BOS,Boston Celtics,0022400811,2025-02-23,BOS vs. NYK,W,242,118,45,91,0.495,17,44,0.386,11,11,1.000,12,37,49,27,8,5,10,14,13.0,118.80,43.200000,0.492400,18.800000,0.4022,13.60,0.84660,10.2,38.8,26.600000,3.600000,5.80,11.00,15.400000
484,22024,1610612738,BOS,Boston Celtics,0022400829,2025-02-25,BOS @ TOR,W,241,111,44,93,0.473,15,51,0.294,8,8,1.000,12,27,39,24,9,4,14,16,10.0,118.40,43.000000,0.488000,19.000000,0.3930,13.40,0.88660,10.4,40.4,26.000000,4.800000,5.60,10.20,14.800000
468,22024,1610612738,BOS,Boston Celtics,0022400836,2025-02-26,BOS @ DET,L,240,97,33,80,0.413,21,49,0.429,10,15,0.667,7,25,32,21,9,1,17,15,-20.0,114.40,42.600000,0.474400,18.200000,0.3544,11.00,0.92000,10.6,38.4,26.600000,5.400000,5.00,11.00,13.800000
437,22024,1610612738,BOS,Boston Celtics,0022400852,2025-02-28,BOS vs. CLE,L,240,116,43,89,0.483,17,39,0.436,13,17,0.765,14,26,40,20,5,5,11,19,-7.0,113.20,41.400000,0.465200,19.000000,0.3760,11.40,0.85340,11.4,33.6,26.000000,6.400000,4.20,13.20,14.600000
417,22024,1610612738,BOS,Boston Celtics,0022400866,2025-03-02,BOS vs. DEN,W,240,110,37,78,0.474,14,34,0.412,22,27,0.815,10,35,45,26,7,4,14,18,7.0,113.20,41.600000,0.469400,18.800000,0.3978,11.20,0.87300,11.2,30.6,25.000000,6.800000,4.20,12.40,16.000000
357,22024,1610612738,BOS,Boston Celtics,0022400891,2025-03-05,BOS vs. POR,W,240,128,45,97,0.464,23,54,0.426,15,17,0.882,18,34,52,24,5,6,9,14,10.0,110.40,40.400000,0.467600,16.800000,0.3914,12.80,0.84940,11.0,30.0,23.600000,7.600000,3.80,13.20,16.400000
343,22024,1610612738,BOS,Boston Celtics,0022400900,2025-03-06,BOS vs. PHI,W,240,123,46,91,0.505,19,48,0.396,12,13,0.923,16,30,46,32,8,6,10,16,18.0,112.40,40.400000,0.461400,18.000000,0.3994,13.60,0.82580,12.2,29.4,23.000000,7.000000,4.00,13.00,16.400000
312,22024,1610612738,BOS,Boston Celtics,0022400918,2025-03-08,BOS vs. LAL,W,241,111,40,84,0.476,13,38,0.342,18,25,0.720,11,32,43,24,9,5,9,11,10.0,114.80,40.800000,0.467800,18.800000,0.4198,14.40,0.81040,13.0,30.0,24.600000,6.800000,4.40,12.20,16.400000
268,22024,1610612738,BOS,Boston Celtics,0022400929,2025-03-10,BOS vs. UTA,W,238,114,40,93,0.430,18,53,0.340,16,18,0.889,12,35,47,28,11,8,9,12,6.0,117.60,42.200000,0.480400,17.200000,0.4024,16.00,0.82100,13.8,31.4,25.200000,6.800000,5.20,10.60,15.600000
247,22024,1610612738,BOS,Boston Celtics,0022400946,2025-03-12,BOS vs. OKC,L,240,112,41,94,0.436,20,63,0.317,10,12,0.833,15,26,41,25,9,6,13,25,-6.0,117.20,41.600000,0.469800,17.400000,0.3832,16.60,0.84580,13.4,33.2,26.800000,8.000000,5.80,10.20,14.200000
215,22024,1610612738,BOS,Boston Celtics,0022400958,2025-03-14,BOS @ MIA,W,241,103,36,83,0.434,19,50,0.380,12,13,0.923,9,32,41,18,8,4,14,17,12.0,117.60,42.400000,0.462200,18.600000,0.3642,14.20,0.84940,14.4,31.4,26.600000,8.400000,6.20,10.00,15.600000
198,22024,1610612738,BOS,Boston Celtics,0022400968,2025-03-15,BOS @ BKN,W,240,115,44,84,0.524,13,38,0.342,14,19,0.737,13,25,38,29,5,7,7,14,2.0,112.60,40.600000,0.456200,17.800000,0.3550,13.60,0.85760,12.6,31.0,25.400000,9.000000,5.80,11.00,16.200000
154,22024,1610612738,BOS,Boston Celtics,0022400994,2025-03-18,BOS vs. BKN,W,240,104,35,79,0.443,16,48,0.333,18,22,0.818,6,42,48,24,6,5,13,14,8.0,111.00,40.200000,0.460000,16.600000,0.3442,14.00,0.82040,12.0,30.0,24.800000,8.400000,6.00,10.40,15.800000
100,22024,1610612738,BOS,Boston Celtics,0022401020,2025-03-21,BOS @ UTA,W,240,121,45,97,0.464,17,51,0.333,14,16,0.875,16,32,48,27,13,4,10,15,22.0,109.60,39.200000,0.453400,17.200000,0.3424,14.00,0.84000,11.0,32.0,24.800000,7.800000,6.00,11.20,16.400000
75,22024,1610612738,BOS,Boston Celtics,0022401034,2025-03-23,BOS @ POR,W,241,129,48,88,0.545,23,50,0.460,10,14,0.714,11,27,38,31,6,6,9,14,13.0,111.00,40.200000,0.460200,17.000000,0.3410,13.60,0.83720,11.8,31.4,24.600000,8.200000,5.20,11.40,17.000000
64,22024,1610612738,BOS,Boston Celtics,0022401044,2025-03-24,BOS @ SAC,W,240,113,41,90,0.456,19,50,0.380,12,20,0.600,10,35,45,28,9,4,10,14,18.0,114.40,41.600000,0.482000,17.600000,0.3696,13.60,0.81340,11.0,31.6,25.800000,7.600000,5.20,10.60,14.800000
39,22024,1610612738,BOS,Boston Celtics,0022401058,2025-03-26,BOS @ PHX,W,239,132,45,89,0.506,22,52,0.423,20,22,0.909,11,37,48,33,8,7,10,18,30.0,116.40,42.600000,0.486400,17.600000,0.3696,13.60,0.74880,11.2,32.2,27.800000,7.800000,5.20,9.80,14.200000

## Feature Definitions

Each row represents a matchup between two teams.  
TEAM_NAME: Name of the home team. All team statistics count that season's games up to but not including the current game
Days-Rest-Home: The difference in days between the current game and the home team's previous game
GP: games played by the home team
W: wins by the home team
L: losses by the home team
W_PCT: win percentage of the home team
MIN: total minutes  
FGM: Made field goals  
FGA: attempted field goals  
FG_PCT: percentage of field goals made  
FG3M: three point field goals made  
FG3A: three point field goals attempted  
FG3_PCT: percentage of three point field goals made  
FTM: free throws made  
FTA: free throws attempted   
FT_PCT: percentage of free throws made  
OREB: offensive rebounds  
DREB: defensive rebounds  
REB: total rebounds  
AST: assists  
TOV: turnovers  
STL: steals  
BLK: blocks  
BLKA: blocks against  
PF: personal fouls   
PFD: personal fouls drawn  
PTS: total points  
PLUS_MINUS: point differential   
TEAM_NAME.1: Name of the away team. The away team's statistics are represented with a '.1' suffix  
Days-Rest-Away: Days of rest since the away team's previous game
Date(str): Date of the game in format '2012-11-04'  
Home-Team-Win(float): A boolean representing whether the home team won the game  
Score(float): The total score for the game  
OU(float): The predicted over-under value by the sportsbook before the game  
OU-Cover(float): Whether the game's total score exceeded the over under

# TODO:
Where is the over under coming from for these games before gambling was legal?  
Clean data: convert to ints, remove highly correlated features, remove ranks  
minutes: include to normalize overtime games  
points: normalize based on average for a season
data warehousing: store the data in a way so that it is easier to run high level queries eg. get all of the Lakers games for the 2024-2025 season: model for team, game, and season
The goal is to create sequences of the previous 5 games for each team including statistics for and statistics allowed